name: Release Build, Test, and Deploy

on:
  create:
    branches:
      - "release/**"
  push:
    branches:
      - "release/**"
    paths-ignore:
      - README.md
      - .gitignore
  pull_request:
    branches:
      - "release/**"
    paths-ignore:
      - README.md
      - .gitignore

permissions:
  contents: read
  actions: read
  checks: write

jobs:
  build:
    env:
      BUILD_CONFIG: 'Release'

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
  
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore PandaLabs_RPGManager.sln

    - name: Build
      run: dotnet build PandaLabs_RPGManager.sln --no-restore --configuration $BUILD_CONFIG

    - name: Test
      run: dotnet test PandaLabs_RPGManager.sln --no-build --verbosity normal --configuration $BUILD_CONFIG --logger "trx;LogFileName=test-results.trx" || true

    - name: Test Report
      uses: dorny/test-reporter@v1
      if: always()
      with:
        name: DotNET Tests
        path: "**/test-results.trx"                            
        reporter: dotnet-trx
        fail-on-error: true

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_EMAIL }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Presentation/API/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/pandalabsrpgapi:latest, ${{ secrets.DOCKERHUB_USERNAME }}/pandalabsrpgapi:${{ github.run_number }}
